import itertools

keywords = ["universitykalilinux", "universityofkalilinux"]
numbers = ['123', '2025', '456', '789']
special_chars = ['!', '@', '#', '$', '%', '^', '&', '*']
cases = [s.lower() for s in keywords] + [s.upper() for s in keywords]

passwords = set()

for keyword in cases:
    for number in numbers:
        passwords.add(keyword + number)
        passwords.add(number + keyword)
        for char in special_chars:
            passwords.add(keyword + char)
            passwords.add(char + keyword)
            passwords.add(keyword + number + char)
            passwords.add(char + number + keyword)

with open("password_list.txt", "w") as f:
    for password in passwords:
        f.write(password + "\n")

print("Password list generated by University of Kali Linux and saved to password_list.txt")
